import type { NextPage } from 'next';
import { WalletDisconnectButton, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useWallet } from '@solana/wallet-adapter-react';
import { SnackbarProvider } from 'notistack';
import Swap from './swap';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    This a POC of <a href=""></a> <a>Swap</a>
                </h1>

                <div className={styles.walletButtons}>
                    <WalletMultiButton />
                    <WalletDisconnectButton />
                </div>

                {/* <p className={styles.description}>
                    Get started by editing <code className={styles.code}>pages/index.tsx</code>
                </p> */}

                <div style={{ height: '50px' }}/>
                <div className={styles.grid}>
                    {/* <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Swappp &rarr;</h2>
                        <p>TODO</p>
                    </a> */}
                    <SnackbarProvider maxSnack={5} autoHideDuration={8000}>
                        <Swap />
                    </SnackbarProvider>

                </div>
            </main>
        </div>
    );
};

export default Home;
